# Generated by Django 4.1.7 on 2023-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_city_city_id_city_country_city_iso2_city_iso3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='admin_name',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
