# Generated by Django 4.1.7 on 2023-03-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_city_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='capital',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
